# -*- coding: utf-8 -*-
"""Copia de ACTIVIDAD 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1TMDNNbSEFKX94asb0qbLGP8S4wUITc

# Estudio de caso Proyectos de regalía

## Contexto

El presente estudio analiza información histórica de proyectos asociados a convocatorias de regalías, con el propósito de identificar características que permitan diferenciar sus estados finales. La base contiene información sobre las entidades participantes, aliados, rol de la UDFJC, año, duración y valor de los proyectos.

Para proteger la privacidad de la información, los datos fueron anonimizados, evitando utilizar información que permita identificar directamente a personas. El análisis se centra únicamente en las características generales de los proyectos y sus resultados.

De manera descriptiva y estadística, se busca identificar diferencias y asociaciones entre las características de los proyectos y su estado final, con especial interés en determinar si la relación con MinCiencias constituye un factor diferenciador.

A partir de lo anterior, se plantea la siguiente pregunta:

¿Qué variables y características de los proyectos históricos tienen mayor capacidad para diferenciar los estados finales en las convocatorias de regalías?

# 1. Exploración y validación de datos
En esta etapa se realiza una revisión inicial del conjunto de datos con el propósito de conocer su estructura y verificar su calidad. Se identifica la cantidad de registros y variables, los tipos de datos de cada columna, la presencia de valores faltantes, la distribución de los proyectos según su estado final y la cantidad de valores diferentes en cada variable
"""

#Librerias a usar para el desarrollo del codigo

import numpy as np
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt
import scipy as sp
import seaborn as sns

url = 'https://raw.githubusercontent.com/camilorobledo0-creator/Actividad-5/refs/heads/main/Propuestas%20Investigacion-1.csv'
dataini = pd.read_csv(url, sep=';')

data = dataini.copy()
data.shape

data.columns

data.info()

data.shape
data.info()
data.isnull().sum()
data['ESTADO'].value_counts()
data.nunique()

print(data['PROGRAMA'].value_counts())

data['ALIADO'].value_counts()

data['PROGRAMA'].value_counts()

"""#Creación de la variable MinCiencias
Debido a que uno de los aspectos centrales del análisis es determinar si la relación con MinCiencias puede diferenciar los estados finales de los proyectos, se crea una nueva variable booleana a partir de la columna ENTIDAD. Esta variable permite identificar mediante los valores True y False si cada registro presenta o no una relación con MinCiencias.
"""

data['ENTIDAD'].value_counts()

data['es_MinCiencias'] = data['ENTIDAD'].str.contains('MinCiencias',case=False, na=False)
data[['ENTIDAD', 'es_MinCiencias']].head(10)

"""#Selección de variables para el análisis
A partir de la exploración inicial de la base de datos, se seleccionan las variables que serán utilizadas en el análisis. La variable ESTADO se establece como variable de interés, debido a que representa el resultado final de los proyectos.
Como variables explicativas se consideran ENTIDAD, ALIADO, ROL UDFJC, AÑO, MESES y VALOR PROYECTO. Adicionalmente, se incorpora la variable es_MinCiencias, creada a partir de ENTIDAD, con el propósito de analizar si la relación con MinCiencias presenta alguna asociación con el estado final de los proyectos.

Se realiza la transformación de la variable VALOR PROYECTO para convertir los valores almacenados como texto a un formato numérico que permita realizar cálculos estadísticos. Para ello, se eliminan símbolos monetarios, separadores y espacios que pueden impedir su correcta interpretación. Posteriormente, se convierten los valores a formato numérico y se agrupan los proyectos según su ESTADO, calculando el número de registros, promedio, mediana, valor mínimo y valor máximo. Estos indicadores permiten realizar una primera comparación descriptiva del valor de los proyectos entre los diferentes estados finales.
"""

data['VALOR PROYECTO'] = data['VALOR PROYECTO'].astype(str).str.replace('$', '', regex=False).str.replace('€', '', regex=False).str.replace('.', '', regex=False).str.replace(',', '.', regex=False).str.replace(' ', '', regex=False).str.replace('-', '', regex=False)
data['VALOR PROYECTO'] = pd.to_numeric(data['VALOR PROYECTO'], errors='coerce')
data.groupby('ESTADO')['VALOR PROYECTO'].agg(['count', 'mean', 'median', 'min', 'max'])

data['ESTADO'].value_counts()

(data['ESTADO'].value_counts(normalize=True) * 100).round(2)

"""###Interpetacion sobre porcentaje y valor del proyecto
La distribución de los proyectos según su estado final muestra una mayor concentración en la categoría No Avalada, que representa el 59,34 % de los registros, seguida de Contrato firmado (14,10 %), Desistio (8,85 %), Seleccionada (7,54 %), Avalada (5,57 %) y En tramite (4,59 %). Al comparar estas categorías con el VALOR PROYECTO, se observan diferencias tanto en los promedios como en las medianas y en los rangos de valores. En particular, algunas categorías presentan una diferencia considerable entre el promedio y la mediana, lo que evidencia que existen proyectos con valores elevados que pueden influir en el promedio. Por lo tanto, los resultados descriptivos sugieren que el valor de los proyectos presenta comportamientos diferentes según el estado final, pero estas diferencias deben ser contrastadas mediante una prueba estadística para determinar si existe una diferencia significativa entre los grupos.

#Creación del DataFrame de análisis
Con el propósito de organizar el análisis y trabajar únicamente con las variables seleccionadas para el estudio, se crea un nuevo DataFrame a partir de la información contenida en data. Este DataFrame conserva las variables relacionadas con el estado final de los proyectos, las características de las entidades y aliados, el rol de la UDFJC, el año, la duración, el valor del proyecto y la variable es_MinCiencias.
"""

df = data[['ESTADO', 'ENTIDAD', 'ALIADO', 'ROL UDFJC', 'AÑO', 'MESES', 'VALOR PROYECTO', 'es_MinCiencias']].copy()
df.head()

df.groupby(['ENTIDAD', 'ESTADO']).size().sort_values(ascending=False)

df.groupby(['ALIADO', 'ESTADO']).size().sort_values(ascending=False)

resultado_aliado = df.groupby(['ALIADO', 'ESTADO']).size().sort_values(ascending=False)
print(resultado_aliado)

resultado_rol = df.groupby(['ROL UDFJC', 'ESTADO']).size().sort_values(ascending=False)
print(resultado_rol)

conteo = data.groupby(['ENTIDAD', 'ESTADO']).size()
total = data.groupby('ENTIDAD').size().sort_values(ascending=False)
print(total)

"""La distribución de los proyectos por entidad presenta una alta concentración de registros en MinCiencias, con 214 proyectos, mientras que las demás entidades cuentan con una cantidad considerablemente menor de registros. Esta diferencia debe tenerse en cuenta al interpretar los porcentajes por estado, especialmente en entidades con pocos proyectos, ya que sus porcentajes pueden estar determinados por un número reducido de observaciones."""

conteo = data.groupby(['ENTIDAD', 'ESTADO']).size()
total = data.groupby('ENTIDAD').size()
porcentaje = ((conteo / total) * 100).sort_values(ascending=False)
print(porcentaje)

tabla_rol = df.groupby(['ROL UDFJC', 'ESTADO']).size().unstack(fill_value=0)
tabla_rol

tabla_min = df.groupby(['es_MinCiencias', 'ESTADO']).size().unstack(fill_value=0)
tabla_min

"""# Indicadores KPI
Se construyeron indicadores KPI para realizar una caracterización descriptiva de los proyectos y observar su comportamiento según el estado final. Se calcularon cantidades, porcentajes y medidas como la mediana para identificar diferencias iniciales entre los grupos.
"""

kpi_min = tabla_min.div(tabla_min.sum(axis=1), axis=0) * 100
kpi_min
kpi_min.round(2)

"""La distribución porcentual muestra que existen diferencias en los estados finales entre los proyectos relacionados y no relacionados con MinCiencias. En los proyectos relacionados con MinCiencias, el 68,22 % corresponde al estado No Avalada, mientras que en los proyectos no relacionados este estado representa el 38,46 %. También se presentan diferencias en los estados Avalada y Desistio, lo que permite observar un comportamiento diferente entre ambos grupos.

Se transforma la variable MESES a formato numérico para permitir su análisis estadístico. Posteriormente, se calcula la mediana de la duración de los proyectos para cada categoría de ESTADO. Este indicador permite comparar la duración típica de los proyectos entre los diferentes estados finales y observar posibles diferencias en su comportamiento.
"""

kpi_meses = df.groupby('ESTADO')['MESES'].median()
kpi_meses

kpi_valor = df.groupby('ESTADO')['VALOR PROYECTO'].median()
kpi_valor

"""Primero agrupamos los proyectos por estado y calculamos la mediana de su valor. Después damos formato a los resultados: agregamos el signo de pesos, colocamos separadores de miles y eliminamos los decimales para que los valores monetarios sean más fáciles de leer. Este segundo código solamente cambia la presentación del resultado, no modifica el valor calculado.

Usamos lambda porque necesitamos aplicar una función sencilla a cada resultado del KPI. En este caso, lambda toma cada valor, lo convierte a formato monetario, agrega el signo de pesos, coloca separadores de miles y elimina los decimales. Es decir, lambda nos permite hacer esta transformación de manera rápida sin tener que crear una función aparte.
"""

kpi_valor.apply(lambda x: f"${x:,.0f}")

"""La mediana del valor de los proyectos presenta diferencias entre las categorías de estado final. Los valores típicos más altos se observan en los estados Avalada y En tramite, mientras que los valores más bajos corresponden a Seleccionada y Contrato firmado. Estas diferencias son descriptivas y deberán ser contrastadas posteriormente mediante una prueba estadística para determinar si existe evidencia de diferencias significativas entre los estados.

#Pruedas Estadisticas
En esta etapa se realiza la caracterización de las variables seleccionadas para el estudio, con el propósito de conocer su comportamiento y facilitar la identificación de posibles diferencias entre los estados finales de los proyectos.

Las variables seleccionadas se clasifican en categóricas, discretas y continuas. Las variables ESTADO, ENTIDAD, ALIADO, ROL UDFJC y es_MinCiencias son categóricas, porque representan grupos o categorías. AÑO y MESES son variables discretas, porque toman valores numéricos enteros. VALOR PROYECTO es una variable continua, ya que representa un valor monetario que puede tomar diferentes valores dentro de un rango.

Se analizarán principalmente las variables numéricas VALOR PROYECTO y MESES. Para VALOR PROYECTO se observará la distribución de los valores mediante un histograma y se comparará su comportamiento entre las diferentes categorías de ESTADO mediante un gráfico de cajas. Para MESES se realizará una comparación de su comportamiento según el estado final.

La selección de los métodos estadísticos se realiza de acuerdo con el tipo de variable y con lo que se busca analizar. Para las variables numéricas, como VALOR PROYECTO, MESES y AÑO, se utilizará la prueba ANOVA, ya que permite comparar las medias de estas variables entre los diferentes estados finales y determinar si existen diferencias estadísticamente significativas. Para las variables categóricas, como es_MinCiencias, ALIADO y ROL UDFJC, se utilizará la prueba de Chi-cuadrado, porque permite determinar si existe una asociación entre estas variables y el ESTADO final de los proyectos.

Chi-cuadrado: Este número mide qué tan diferentes son los resultados
p-valor: Es un número que calcula la prueba estadística para medir qué tan compatibles son nuestros resultados
Grados de libertad: Los grados de libertad representan la cantidad de categorías que pueden variar independientemente teniendo en cuenta las restricciones de los totales.
"""

from scipy.stats import chi2_contingency
chi2, p, gl, esperados = chi2_contingency(tabla_min)

print("Chi-cuadrado:", chi2)
print("p-valor:", p)
print("Grados de libertad:", gl)

"""0.000000378 < 0.05 - se rechaza la hipótesis nula (H₀)

H₀: no existe relación entre es_MinCiencias y ESTADO.
H₁: existe relación entre es_MinCiencias y ESTADO.

La prueba de Chi-cuadrado presentó un estadístico de 37,99, con 5 grados de libertad y un p-valor de 3,78 × 10⁻⁷. Debido a que el p-valor es menor que el nivel de significancia establecido de 0,05, se rechaza la hipótesis nula de independencia.

Por lo tanto, existe evidencia estadísticamente significativa de una asociación entre la variable es_MinCiencias y el ESTADO final de los proyectos. Este resultado indica que la distribución de los estados finales presenta diferencias entre los proyectos relacionados y no relacionados con MinCiencias.

F nos ayuda a saber si las diferencias entre los grupos son grandes en comparación con la variación que existe dentro de los propios grupos. p-valor: Es un número que calcula la prueba estadística para medir qué tan compatibles son nuestros resultados
"""

from scipy.stats import f_oneway
grupos_meses = [grupo['MESES'].dropna()
    for estado, grupo in df.groupby('ESTADO')]

resultado_anova_meses = f_oneway(*grupos_meses)
print('Estadístico F:', resultado_anova_meses.statistic)
print('p-valor:', resultado_anova_meses.pvalue)

"""H₀: las medias de duración de los proyectos son iguales entre los diferentes estados finales.
H₁: al menos una de las medias de duración es diferente.

La prueba ANOVA presentó un estadístico F de 1,13, con un p-valor de 0,3420. Debido a que el p-valor es mayor que el nivel de significancia establecido de 0,05, no se rechaza la hipótesis nula.

Por lo tanto, no existe evidencia estadísticamente significativa para afirmar que la media de duración de los proyectos sea diferente entre los estados finales. Aunque se observaron algunas diferencias descriptivas en la duración de los proyectos, estas no resultaron estadísticamente significativas según la prueba ANOVA realizada.
"""

from scipy.stats import f_oneway
grupos_valor = [grupo['VALOR PROYECTO'].dropna()
    for estado, grupo in df.groupby('ESTADO')]

resultado_anova_valor = f_oneway(*grupos_valor)

print('Estadístico F:', resultado_anova_valor.statistic)
print('p-valor:', resultado_anova_valor.pvalue)

"""H₀: las medias del valor de los proyectos son iguales entre los diferentes estados finales.
H₁: al menos una de las medias del valor de los proyectos es diferente.

La prueba ANOVA presentó un estadístico F de 2,82, con un p-valor de 0,0167. Debido a que el p-valor es menor que el nivel de significancia establecido de 0,05, se rechaza la hipótesis nula.

Por lo tanto, existe evidencia estadísticamente significativa para afirmar que la media del valor de los proyectos presenta diferencias entre al menos algunos de los estados finales.
"""

from scipy.stats import f_oneway
grupos_año = [    grupo['AÑO'].dropna()
    for estado, grupo in df.groupby('ESTADO')]

resultado_anova_año = f_oneway(*grupos_año)

print('Estadístico F:', resultado_anova_año.statistic)
print('p-valor:', resultado_anova_año.pvalue)

"""H₀: las medias del año de los proyectos son iguales entre los diferentes estados finales.
H₁: al menos una de las medias del año de los proyectos es diferente.

La prueba ANOVA presentó un estadístico F de 27,79, con un p-valor de 4,20 × 10⁻²³. Debido a que el p-valor es menor que el nivel de significancia establecido de 0,05, se rechaza la hipótesis nula.

Por lo tanto, existe evidencia estadísticamente significativa para afirmar que la media del año de los proyectos presenta diferencias entre al menos algunos de los estados finales.
"""

from scipy.stats import chi2_contingency
chi2, p, gl, esperados = chi2_contingency(tabla_aliado)

print('Chi-cuadrado:', chi2)
print('p-valor:', p)
print('Grados de libertad:', gl)

"""H₀: no existe relación entre ALIADO y ESTADO.
H₁: existe relación entre ALIADO y ESTADO.

La prueba de Chi-cuadrado presentó un estadístico de 1164,37, con 1120 grados de libertad y un p-valor de 0,1737. Debido a que el p-valor es mayor que el nivel de significancia establecido de 0,05, no se rechaza la hipótesis nula de independencia.

Por lo tanto, no existe evidencia estadísticamente significativa para afirmar que exista una asociación entre la variable ALIADO y el ESTADO final de los proyectos.
"""

from scipy.stats import chi2_contingency
chi2, p, gl, esperados = chi2_contingency(tabla_rol)

print('Chi-cuadrado:', chi2)
print('p-valor:', p)
print('Grados de libertad:', gl)

"""H₀: no existe relación entre ROL UDFJC y ESTADO. H₁: existe relación entre ROL UDFJC y ESTADO.

La prueba de Chi-cuadrado presentó un estadístico de 60,56, con 25 grados de libertad y un p-valor de 8,75 × 10⁻⁵. Debido a que el p-valor es menor que el nivel de significancia establecido de 0,05, se rechaza la hipótesis nula de independencia.

#Conclusión

A partir del análisis realizado sobre los proyectos históricos de regalías, se identificaron diferencias estadísticamente significativas en algunas de las variables estudiadas frente al estado final de los proyectos. En particular, se encontró evidencia de asociación entre la relación con **MinCiencias** y el `ESTADO` final, así como entre el `ROL UDFJC` y el `ESTADO`. De igual manera, las variables `AÑO` y `VALOR PROYECTO` presentaron diferencias estadísticamente significativas entre los diferentes estados finales.

Por otra parte, las variables `MESES` y `ALIADO` no presentaron evidencia estadísticamente significativa de diferencias o asociación con el estado final, de acuerdo con las pruebas realizadas. Aunque se observaron diferencias descriptivas en estas variables, estas no fueron suficientes para establecer una relación estadísticamente significativa.

En particular, la relación con MinCiencias mostró diferencias importantes en la distribución de los estados finales: el **68,22 % de los proyectos relacionados con MinCiencias corresponde a proyectos No Avalados**, mientras que este estado representa el **38,46 % de los proyectos no relacionados**. Este resultado, junto con la prueba de Chi-cuadrado, evidencia una asociación estadísticamente significativa entre ambas variables.

En conjunto, los resultados permiten identificar que **la relación con MinCiencias, el rol de la UDFJC, el año y el valor del proyecto presentan evidencia estadística de diferenciación respecto al estado final**, mientras que `ALIADO` y `MESES` no muestran evidencia estadística suficiente en los datos analizados. Estos resultados permiten responder parcialmente la pregunta analítica planteada y proporcionan una base para interpretar los factores que presentan mayor capacidad de diferenciación dentro del conjunto histórico estudiado. No obstante, los resultados representan asociaciones y diferencias estadísticas dentro de la base analizada y **no permiten establecer relaciones de causalidad**.

#Visualización de los resultados
En esta etapa se presentan representaciones gráficas de las variables y resultados obtenidos durante el análisis. Los gráficos permiten facilitar la comparación entre los diferentes estados finales de los proyectos e identificar visualmente diferencias en su distribución, duración y valor. Para las visualizaciones se utiliza la biblioteca Seaborn
"""

sns.countplot(data=df, x='ESTADO')
plt.title('Distribución de proyectos según estado final')
plt.xlabel('Estado final')
plt.ylabel('Cantidad de proyectos')
plt.xticks(rotation=45)
plt.show()

"""La gráfica muestra que los proyectos no se distribuyen de manera uniforme entre los diferentes estados finales. Se observa una mayor concentración de proyectos en el estado No Avalada, mientras que categorías como Avalada, Desistio, En trámite y Seleccionada presentan una cantidad menor de registros. Esto indica que dentro de la base analizada existen diferencias importantes en el número de proyectos que pertenecen a cada estado.

En general, la gráfica permite identificar cómo se concentra la información de la base y sirve como punto de partida para analizar si las características de los proyectos presentan comportamientos diferentes según su estado final.
"""

sns.boxplot(data=df, x='VALOR PROYECTO', y='ESTADO')
plt.title('Distribución del valor de los proyectos según estado final')
plt.xlabel('Valor del proyecto')
plt.ylabel('Estado final')

"""La gráfica permite observar que el valor de los proyectos presenta comportamientos diferentes entre los estados finales. Se identifican diferencias en la posición de las medianas y en la dispersión de los valores, lo que indica que los proyectos no tienen una distribución económica igual en todas las categorías de estado.

También se observan algunos valores considerablemente altos que se encuentran alejados de la mayor concentración de los datos. Estos valores extremos pueden influir en la media, razón por la cual se utilizó la mediana como indicador principal para describir el valor típico de los proyectos.

La gráfica muestra, por tanto, que existe un comportamiento descriptivamente diferente del valor de los proyectos según su estado final.
"""

sns.boxplot(data=df, x='MESES', y='ESTADO')
plt.title('Distribución de la duración de los proyectos según estado final')
plt.xlabel('Duración del proyecto (meses)')
plt.ylabel('Estado final')
plt.show()

"""La gráfica muestra que la duración de los proyectos presenta algunas diferencias descriptivas entre los estados finales. Se observa que varios estados tienen una duración central cercana a 24 meses, mientras que Seleccionada y Contrato firmado presentan valores centrales inferiores. Esto permite identificar visualmente que la duración de los proyectos no se comporta exactamente de la misma manera en todas las categorías.
En consecuencia, la variable MESES permite describir el comportamiento de los proyectos, pero con los datos analizados no presenta evidencia estadística suficiente para considerarla una variable diferenciadora de los estados finales.

Las gráficas nos permiten identificar visualmente patrones y diferencias en los datos. Sin embargo, una diferencia visual no significa necesariamente que sea estadísticamente significativa. Por eso complementamos la interpretación gráfica con las pruebas estadísticas. En nuestro análisis, el valor del proyecto presentó diferencias estadísticamente significativas entre los estados, mientras que la duración de los proyectos mostró diferencias descriptivas, pero no estadísticamente significativas.

# Recomendaciones y líneas de investigación futura

Como línea de investigación futura, se recomienda profundizar de manera controlada en las variables que presentaron diferencias o asociaciones estadísticamente significativas, especialmente la relación con MinCiencias, el año, el valor del proyecto y el rol de la UDFJC. Este análisis podría complementarse con información adicional de los proyectos y con una mayor cantidad de registros, con el propósito de comprender mejor los factores asociados a los diferentes estados finales.

También se recomienda profundizar en variables con alta cantidad de categorías, como ALIADO, debido a que la distribución de los registros es desigual y limita la interpretación de los resultados estadísticos. Estas líneas futuras permitirían ampliar el análisis sin asumir relaciones causales y manteniendo el alcance exploratorio del estudio.
"""